name: evestlund
favicon: null
layout_spectrum: 0.13039701175875962
typography_spectrum: 0.09418056579306722
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.051626019878312945
  lightness: 0.7432389571331441
  saturation: 0.362715921131894
  rhythmicContrast: 0.711006372468546
purpose: []
